apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro-app-deploy
spec:
  selector:
    matchLabels:
      app: vpro-app
  template:
    metadata:
      labels:
        app: vpro-app
    spec:
      containers:
      - name: vpro-app
        image: vprofile/vproapp:V1
        resources:
          limits:
            memory: "800M"
            cpu: "1"
        ports:
        - name: vpro-app-port
          containerPort: 8080